name: Daily CURL Request

on:
  workflow_dispatch:
  schedule:
    # Runs at 0:55 AM AEST (UTC+10:00) every day.
    - cron: '55 14 * * *'

jobs:
  curl_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the start and end of day in AEST
        id: dates
        run: |
          echo "Generating timestamps..."
          const date = new Date();
          const year = date.getFullYear();
          const month = (`0${date.getMonth() + 1}`).slice(-2);
          const day = (`0${date.getDate()}`).slice(-2);
          const dateFrom = new Date(`${year}-${month}-${day}T00:00:00+10:00`).getTime();
          const dateTo = new Date(`${year}-${month}-${day}T23:59:59+10:00`).getTime();
      
          console.log(`::set-output name=dateFrom::${dateFrom}`);
          console.log(`::set-output name=dateTo::${dateTo}`);
          shell: node -e {0}

      - name: Run CURL command
        run: |
          curl "https://api.prod.aws.queensland.com/search?category=events&countryCode=au_en&dateFrom=${{ steps.compute-dates.outputs.dateFrom }}&dateTo=${{ steps.compute-dates.outputs.dateTo }}&destination=all-queensland&disabledClassificationsFilter=true&rawCategory=event" > events.json

      - name: Commit events file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch --unshallow || true
          git add events.json
          if git diff --cached --exit-code; then
            echo 'No changes in events.json, skipping commit.'
          else
            git commit -m "Daily update of events.json"
            git push
          fi
