name: Daily CURL Request

on:
  workflow_dispatch:
  schedule:
    # Runs at 0:55 AM AEST (UTC+10:00) every day.
    - cron: '55 14 * * *'

jobs:
  curl_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Calculate epoch values for today and tomorrow
        id: date-calculation
        run: |
          # Calculate 'dateFrom' for today at the start of the day (00:00:00)
          DATE_FROM=$(date -u +"%s" -d "today 00:00:00")
          # Multiply by 1000 to convert seconds to milliseconds
          DATE_FROM_MS=$((DATE_FROM * 1000))
          
          # Calculate 'dateTo' for tomorrow at the start of the day (00:00:00)
          DATE_TO=$(date -u +"%s" -d "tomorrow 00:00:00")
          # Multiply by 1000 to convert seconds to milliseconds
          DATE_TO_MS=$((DATE_TO * 1000))
          
          # Set the values as action's output parameters
          echo "::set-output name=date_from_ms::$DATE_FROM_MS"
          echo "::set-output name=date_to_ms::$DATE_TO_MS"
          
      - name: CURL request to Queensland Events API with dynamic dates
        run: |
          curl -X GET \
          -H "Content-Type: application/json" \
          "https://api.prod.aws.queensland.com/search?category=events&countryCode=au_en&dateFrom=${{ steps.date-calculation.outputs.date_from_ms }}&dateTo=${{ steps.date-calculation.outputs.date_to_ms }}&destination=all-queensland&disabledClassificationsFilter=true&rawCategory=event"

      - name: Commit events file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch --unshallow || true
          git add events.json
          if git diff --cached --exit-code; then
            echo 'No changes in events.json, skipping commit.'
          else
            git commit -m "Daily update of events.json"
            git push
          fi
