name: Daily CURL Request

on:
  workflow_dispatch:
  schedule:
    # Runs at 0:55 AM AEST (UTC+10:00) every day.
    - cron: '55 14 * * *'

jobs:
  curl_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the start and end of day in AEST
        id: dates
        run: |
          # Set timezone to UTC+10 for AEST
          export TZ='Australia/Brisbane'
          # Start of the day (AEST) at 00:00
          dateFrom=$(date -u -d "today" +"%Y-%m-%dT00:00:00Z")
          # End of the day (AEST) at 23:59
          dateTo=$(date -u -d "today" +"%Y-%m-%dT23:59:59Z")
          
          # Convert dates to EPOCH milliseconds
          dateFromEpoch=$(date -u -d "$dateFrom" +%s%3N)
          dateToEpoch=$(date -u -d "$dateTo" +%s%3N)
          
          echo "dateFrom=${dateFromEpoch}" >> $GITHUB_ENV
          echo "dateTo=${dateToEpoch}" >> $GITHUB_ENV

      - name: Run CURL command
        run: |
          curl "https://api.prod.aws.queensland.com/search?category=events&countryCode=au_en&dateFrom=${{ env.dateFrom }}&dateTo=${{ env.dateTo }}&destination=all-queensland&disabledClassificationsFilter=true&rawCategory=event" > events.json
      
      - name: Commit events file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git fetch --unshallow || true
          git add events.json
          if git diff --cached --exit-code; then
            echo 'No changes in events.json, skipping commit.'
          else
            git commit -m "Daily update of events.json"
            git push
          fi
